# Generated by Django 5.2.15 on 2026-08-13 17:32

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgePage',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Question', max_length=255)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(db_index=True, default='anonymous', max_length=100)),
                ('question_text', models.TextField(blank=True, default='')),
                ('resolution_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='qa_app.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='pages', to='qa_app.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='page_images/')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('ocr_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='qa_app.knowledgepage')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['extracted_text'], name='img_ocr_trigm_gin', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgepage',
            index=models.Index(fields=['category', '-created_at'], name='idx_page_cat_created'),
        ),
        migrations.AddIndex(
            model_name='knowledgepage',
            index=models.Index(fields=['category', '-date'], name='idx_page_cat_date'),
        ),
        migrations.AddIndex(
            model_name='knowledgepage',
            index=models.Index(fields=['category', 'username'], name='idx_page_cat_user'),
        ),
        migrations.AddIndex(
            model_name='knowledgepage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='page_title_trigm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgepage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['question_text'], name='page_quest_trigm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgepage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['resolution_text'], name='page_resol_trigm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
