# Generated by Django on 2026-06-12
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgePage',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Question', max_length=255)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(default='anonymous', max_length=100)),
                ('question_text', models.TextField(blank=True, default='')),
                ('resolution_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='qa_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data_url', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='qa_app.knowledgepage')),
            ],
        ),
    ]
