# Generated by Django on 2026-06-12
from django.db import migrations

def seed_initial_records(apps, schema_editor):
    Category = apps.get_model('qa_app', 'Category')
    KnowledgePage = apps.get_model('qa_app', 'KnowledgePage')
    
    general_cat, _ = Category.objects.get_or_create(
        id="cat-1",
        defaults={"name": "General"}
    )
    
    default_pages = [
        {
            "id": "page-1",
            "category": general_cat,
            "title": "How do I reset my password?",
            "date": "2024-05-01",
            "username": "johndoe",
            "question_text": "How do I reset my password?",
            "resolution_text": "To reset your password, click on \"Forgot Password\" on the login page and follow the instructions sent to your email.",
        },
        {
            "id": "page-2",
            "category": general_cat,
            "title": "Can I change my username?",
            "date": "2024-05-02",
            "username": "alice123",
            "question_text": "Can I change my username?",
            "resolution_text": "Usernames cannot be changed once they are set.",
        },
        {
            "id": "page-3",
            "category": general_cat,
            "title": "How do I update my email address?",
            "date": "2024-05-03",
            "username": "bobsmith",
            "question_text": "How do I update my email address?",
            "resolution_text": "Go to Settings > Account > Email and enter your new email address. Don't forget to verify it.",
        },
        {
            "id": "page-4",
            "category": general_cat,
            "title": "Is there a mobile app available?",
            "date": "2024-05-04",
            "username": "sweetpea",
            "question_text": "Is there a mobile app available?",
            "resolution_text": "Yes, our mobile app is available on both iOS and Android. You can download it from the App Store or Google Play.",
        },
        {
            "id": "page-5",
            "category": general_cat,
            "title": "How do I delete my account?",
            "date": "2024-05-05",
            "username": "charlie7",
            "question_text": "How do I delete my account?",
            "resolution_text": "To delete your account, contact our support team and they will assist you with the process.",
        }
    ]
    
    for page in default_pages:
        KnowledgePage.objects.get_or_create(
            id=page["id"],
            defaults={
                "category": page["category"],
                "title": page["title"],
                "date": page["date"],
                "username": page["username"],
                "question_text": page["question_text"],
                "resolution_text": page["resolution_text"]
            }
        )

def rollback_seed_records(apps, schema_editor):
    Category = apps.get_model('qa_app', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_initial_records, reverse_code=rollback_seed_records),
    ]
