# Generated by Django 5.2.15 on 2026-08-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='ocr_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='ocr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
