# Generated by Django 5.2.15 on 2026-06-13 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0006_postgres_trigram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='knowledgepage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pageimage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='knowledgepage',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='knowledgepage',
            index=models.Index(fields=['category', '-created_at'], name='idx_page_cat_created'),
        ),
    ]
