# Generated by Django 5.2.15 on 2026-06-16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0007_alter_category_options_alter_knowledgepage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='knowledgepage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='qa_app.tag'),
        ),
    ]
